### PR TITLE
Added support for aws cli profiles

### PR DESCRIPTION
**Pull request by martintreurnicht**
Resolves https://github.com/lonelyplanet/aws-mfa/issues/13

### CODE REVIEW

**Comment by sciurus** [comment]
This looks good!

**Comment by tobinquadros** [comment]
Thanks! This is great, it's working for me with multiple profiles. Can we get a quick update to the README.md before we merge?

**Comment by martintreurnicht** [comment]
Ok will do

**Comment by tobinquadros** [comment]
Awesome.

**Comment by martintreurnicht** [comment]
Nice!!!

**Pull request merged**
